name: Build SquirrelDefender

on:
  pull_request:
    branches:
      - master
      - dev

jobs:
  build_ubuntu22:
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Make build script executable
        run: chmod +x scripts/run.sh

      - name: Check GHCR_PAT length
        run: echo "Token length: ${#GHCR_PAT}"
        env:
          GHCR_PAT: ${{ secrets.GHCR_PAT }}

      - name: Log in to GHCR with PAT
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u crose72 --password-stdin

      - name: Build SquirrelDefender (BLD_WSL config)
        run: ./scripts/run.sh dev ubuntu-22.04_sm86
